### ISSUE TITLE
Add unit field in the fruit section

### ISSUE THREAD

**Issue by sh7vashrestha** [Senor101/Sagarmatha-Fruits_API#1]
Add a unit field that can take either Kg or piece or dozen(basically rate determination factor)

**Comment by Senor101** [comment]
Should work just as is @sh7vashrestha 
modify your request body just add an extra field of unit. Docs are updated so take a look.
The auth part will be updated and refined soon besides that everything should looks fine. 
Let me know if anything else comes up.
